---
- name: Install dependencies
  apt:
    name:
      - unzip
      - curl
    state: present
    update_cache: yes

- name: Download Consul
  get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
    dest: "/tmp/consul.zip"

- name: Unzip Consul
  unarchive:
    src: "/tmp/consul.zip"
    dest: "/usr/local/bin"
    remote_src: yes

- name: Create Nomad user and group
  user:
    name: "{{ consul_user }}"
    shell: /bin/false
    system: yes
    create_home: no

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  loop:
    - "{{consul_config_dir}}"
    - "{{consul_data_dir}}"

- name: Copy consul config
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    mode: 0644
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
  notify: restart consul

- name: Create systemd unit
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    mode: 0644
  notify: restart consul

- name: Enable and start consul
  systemd:
    name: consul
    enabled: yes
    state: started
