vault_url: "{{ lookup('env', 'ANSIBLE_HASHI_VAULT_ADDR') | default('http://localhost:8200', true) }}"
vault_role_id: "{{ lookup('env', 'ANSIBLE_HASHI_VAULT_ROLE_ID') }}"
vault_secret_id: "{{ lookup('env', 'ANSIBLE_HASHI_VAULT_SECRET_ID') }}"
vault_validate_certs: "{{ lookup('env', 'ANSIBLE_HASHI_VAULT_VALIDATE_CERTS') | default(true, true) }}"

vault_vm_ssh_access_key_mount_point: "proxmox_vms"
vault_vm_ssh_access_key_field: "private_key"
vault_vm_ssh_access_key_path: "{{ inventory_hostname }}"

ssh_key_temp_dir: "./tmp"
ssh_key_temp_path: "{{ ssh_key_temp_dir }}/{{ inventory_hostname }}_id_rsa"
