galaxy_info:
  role_name: k3s_install_local_registry
  author: Stanislaw Horna
  description: Installs local self hosted Docker registry for k3s cluster
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []