---
- name: Install dependencies
  apt:
    name:
      - unzip
      - curl
    state: present
    update_cache: yes

- name: Download Nomad
  get_url:
    url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
    dest: "/tmp/nomad.zip"

- name: Unzip Nomad
  unarchive:
    src: "/tmp/nomad.zip"
    dest: "/usr/local/bin"
    remote_src: yes

- name: Create Nomad user and group
  user:
    name: "{{ nomad_user }}"
    shell: /bin/false
    system: yes
    create_home: no

- name: Add user to the Docker group
  user:
    name: "{{ nomad_user }}"
    groups: docker
    append: yes

- name: Create Nomad directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: "0755"
  loop:
    - "{{ nomad_config_dir }}"
    - "{{ nomad_data_dir }}"
    - "{{ nomad_alloc_dir }}"

- name: Create nomad config
  template:
    src: nomad.hcl.j2
    dest: "{{nomad_config_dir}}/nomad.hcl"
    mode: 0644
  notify: restart nomad

- name: Create systemd unit
  template:
    src: nomad.service.j2
    dest: /etc/systemd/system/nomad.service
    mode: 0644
  notify: restart nomad

- name: Enable and start nomad
  systemd:
    name: nomad
    enabled: yes
    state: started
