galaxy_info:
  role_name: k3s_install_nginx_ingress
  author: Stanislaw Horna
  description: Installs Nginx Ingress Controller for k3s cluster
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []
