galaxy_info:
  role_name: install_docker
  author: Stanislaw Horna
  description: Installs docker on Ubuntu machine
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []