galaxy_info:
  role_name: install_pwsh
  author: Stanislaw Horna
  description: Install Powershell on Ubuntu Server
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []
