- name: Ensure temporary directory exists
  file:
    path: "{{ ssh_key_temp_dir }}"
    state: directory
    mode: "0700"
  delegate_to: localhost
  run_once: true

- name: Fetch SSH private key from Vault
  set_fact:
    ssh_private_key: >-
      {{
        lookup('community.hashi_vault.hashi_vault',
          'secret={{ vault_vm_ssh_access_key_path }}:{{ vault_vm_ssh_access_key_field }}',
          engine_version=2,
          secret_mount_point='{{ vault_vm_ssh_access_key_mount_point }}',
          auth_method='approle',
          auth_mount='approle',
          role_id=lookup('env', 'ANSIBLE_HASHI_VAULT_ROLE_ID'),
          secret_id=lookup('env', 'ANSIBLE_HASHI_VAULT_SECRET_ID'),
          url=vault_url,
          validate_certs=vault_validate_certs
        )
      }}

- name: Write SSH private key to temporary file
  copy:
    content: "{{ ssh_private_key }}"
    dest: "{{ ssh_key_temp_path }}"
    mode: "0600"
  delegate_to: localhost

- name: Set ansible_ssh_private_key_file for connection
  set_fact:
    ansible_ssh_private_key_file: "{{ ssh_key_temp_path }}"
