galaxy_info:
  role_name: hcp_consul
  author: Stanislaw Horna
  description: Sets up HashiCorp Consul on Ubuntu servers.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []