galaxy_info:
  role_name: docker_install_local_registry
  author: Stanislaw Horna
  description: Installs local self hosted Docker registry for docker daemon
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []