galaxy_info:
  role_name: install_gh_cli
  author: Stanislaw Horna
  description: Installs GitHub CLI tool
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []