oh_my_posh_theme_gist_url: "https://gist.githubusercontent.com/StanislawHornaGitHub/9a8e8c01c45f2fe59eb1bbfc846e8d63/raw/0824a12cebd4f959f80e75ebb70e90b9883fb2ab/plain.SH.json"
oh_my_posh_dir: "/usr/share/oh-my-posh"
