galaxy_info:
  role_name: hcp_vault_ssh_setup
  author: Stanislaw Horna
  description: Fetch SSH private key from HashiCorp Vault using AppRole and prepare for the connection
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all

dependencies: []
